### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Joaotcs**
Touchpad/touchscreen patches, config files modification for this + USB mapping config and kext + smart card config and kext

### CODE REVIEW

**Comment by kecinzer** [comment]
Thank you for this, but I have few remarks.

1) What are those first renames in config for HPET and IRQ? Do we need it?
2) What is that USB kext?
3) I don’t use Smart Card, so I don’t need this kext.
4) There is new aml file for BIOS fix, so rename is not needed any more.

Can you please prepare only one commit with change of SSDT-CPD0? Or if you let me I will prepare it with your mention :).

**Comment by Joaotcs** [comment]
Right the rename is not deleted, I forgot, but it is disabled.
Those are recommended stuff, not sure what it really does though xD.
The usbport kext is for the correct USB mapping for our laptoo, way better than using the usbinjectall (in opencore is the xhciportlimit!). Xhciportlimit should only be used temporarily, until you map it properly.

About smartcard, well, it works 100%, and I don't see any difference battery wise, as it is in sleep until you insert a card. But it is a choice of yours ofc.

**Comment by Joaotcs** [comment]
HPET was from this script: https://github.com/corpnewt/FixHPET

**Comment by Joaotcs** [comment]
USBPort i used hackintool to remap for our elitebook g5 in specific. This I can guarantee you that you should use, instead of the xhciportlimit patch.

**Comment by Joaotcs** [comment]
But you can create the file, I can't pull requests of only this file

**Comment by Joaotcs** [comment]
Hpet tries to fix irq conflicts.
"IRQ conflicts result in errors because the CPU can't figure out which device really owns the IRQ number. An IRQ conflict can cause problems severe enough to freeze, or lock up, your computer"

**Comment by kecinzer** [comment]
Thank you for all your explanation. I'm interesting only in USBPort.kext as this may help with better battery life I think.
HPET and IRQ conflicts I don't need, because I don't have any issues, so it's better to keep files clean as possible. I already tried it in past but nothing changed :).

**Comment by kecinzer** [comment]
Thank you for push me about USB ports. I found this guide https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html that I will follow ASAP I get my USB-C device from my office.
It's kind different that your solution.

**Comment by Joaotcs** [comment]
USB mapping with hackintool is way easier and more reliable. Hackintool is a must have app for hackintosh. The GUI of Hackintool makes USB mapping easier and less prone for errors. 
You can use the USB port I made, or make one of yours, and you can disable the smart card if you don't use it. Just be sure to tell that if you upload your usbport without the smart card or any other device ;) 
I have enabled all usable ports, and deleted the ones that have no use for our laptop

**Comment by Joaotcs** [comment]
Add to delete the repo as I have shared my mabook serial numbers...

Going to create my repo, giving you credits: https://github.com/Joaotcs/Hackintosh-Elitebook-8x0-g5/upload/main
Easier for me to update the files

**Comment by kecinzer** [comment]
It's OK, I understand that you made many changes and my new commits causing merge conflicts :).
I already commited your changes. You can see. My USB mapping is little bit different. I made it with all my devices, that can be connected to both USB-A and USB-C.
Snímek obrazovky 2020-10-20 v 18 10 32
And after kext applied and XHCIlimit disabled:
Snímek obrazovky 2020-10-21 v 7 59 30
I'm not sure about type 9/10 for USB-C, but it works as type 10 for now.

**Pull request closed without merging**
